const fs = require('fs');
const path = require('path');
const matter = require('gray-matter');
const { marked } = require('marked');

const recipesDir = path.join(__dirname, 'recipes');
const outputFile = path.join(__dirname, 'recipes.js');

// Get all markdown files recursively
function getMarkdownFiles(dir) {
  const files = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...getMarkdownFiles(fullPath));
    } else if (entry.name.endsWith('.md')) {
      files.push(fullPath);
    }
  }
  return files;
}

// Parse a recipe markdown file
function parseRecipe(filePath, id) {
  const content = fs.readFileSync(filePath, 'utf-8');
  const { data, content: body } = matter(content);

  // Parse ingredients and instructions from markdown body
  const sections = body.split(/^## /m).filter(Boolean);

  let ingredients = [];
  let instructions = [];
  let description = data.description || '';

  for (const section of sections) {
    const [title, ...rest] = section.split('\n');
    const text = rest.join('\n').trim();

    if (title.toLowerCase().includes('ingredient')) {
      ingredients = text.split('\n')
        .map(line => line.replace(/^[-*]\s*/, '').trim())
        .filter(Boolean);
    } else if (title.toLowerCase().includes('instruction')) {
      instructions = text.split('\n')
        .map(line => line.replace(/^\d+\.\s*/, '').replace(/\*\*/g, '').trim())
        .filter(line => line && !line.startsWith('#'));
    }
  }

  return {
    id,
    title: data.title,
    category: data.category,
    image: data.image,
    description,
    ingredients,
    instructions,
    meta: data.meta || '',
    source: data.source || ''
  };
}

// Main build
const files = getMarkdownFiles(recipesDir);
const recipes = files.map((file, i) => parseRecipe(file, i + 1));

const output = `// Auto-generated by build.js - do not edit directly
const recipes = ${JSON.stringify(recipes, null, 2)};
`;

fs.writeFileSync(outputFile, output);
console.log(`Generated ${recipes.length} recipes → recipes.js`);
